### ISSUE TITLE
Date format warnings when running in non-English locale

### ISSUE THREAD

**Issue by mod20388** [deragent/arXivFilter#12]
When running in a non-English locale (fi_FI.utf8), I get warnings like these when processing the arXiv email text:

```
time data '16 Nov 2023 21:30:05 GMT' does not match format '%d %b %Y %H:%M:%S %Z'
time data '17 Nov 2023 14:07:49 GMT' does not match format '%d %b %Y %H:%M:%S %Z'
time data '17 Nov 2023 15:35:57 GMT' does not match format '%d %b %Y %H:%M:%S %Z'
```

These go away when the locale is set to English or C (e.g., running `LC_ALL=en_US.utf8 arxiv-filter` or `LC_ALL=C arxiv-filter`).

**Comment by deragent** [comment]
Thank you for reporting this!

This is definitely a bug, and I definitely was not aware/thinking about, that date parsing (even with a fixed format string) is also locale dependent :)

I will fix this.
